PHONETIC_MAP = {
    "alpha": "A", "alfa": "A", "a": "A", "ay": "A", "eight": "A", "hey": "A",
    "bravo": "B", "b": "B", "bee": "B", "be": "B",
    "charlie": "C", "c": "C", "see": "C", "sea": "C",
    "delta": "D", "d": "D", "dee": "D",
    "echo": "E", "e": "E", "ee": "E",
    "foxtrot": "F", "f": "F", "ef": "F",
    "golf": "G", "g": "G", "gee": "G",
    "hotel": "H", "h": "H", "aitch": "H",
    "india": "I", "i": "I", "eye": "I",
    "juliet": "J", "juliett": "J", "j": "J", "jay": "J",
    "kilo": "K", "k": "K", "kay": "K",
    "lima": "L", "l": "L", "el": "L",
    "mike": "M", "m": "M", "em": "M",
    "november": "N", "n": "N", "en": "N",
    "oscar": "O", "o": "O", "oh": "O", "zero": "O",
    "papa": "P", "p": "P", "pee": "P",
    "quebec": "Q", "q": "Q", "cue": "Q", "queue": "Q",
    "romeo": "R", "r": "R", "are": "R",
    "sierra": "S", "s": "S", "ess": "S",
    "tango": "T", "t": "T", "tee": "T",
    "uniform": "U", "u": "U", "you": "U",
    "victor": "V", "v": "V", "vee": "V",
    "whiskey": "W", "w": "W", "doubleyou": "W", "double you": "W",
    "x-ray": "X", "x": "X", "ex": "X",
    "yankee": "Y", "y": "Y", "why": "Y",
    "zulu": "Z", "z": "Z", "zee": "Z", "zed": "Z",
}
